name = "point-world"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Durable Objects binding
[[durable_objects.bindings]]
name = "POINT_WORLD"
class_name = "PointWorld"

[[migrations]]
tag = "v1"
new_classes = ["PointWorld"]
